- name: create ec2 & r53 through ansible
  hosts: local
  become: true
  connection: local
  vars:
   subnet_id: subnet-0c15405f633ef6962
   sg_id:  sg-00397bd41905b6fbf
   instance_type: t3.micro
   ami_id: ami-0c614dee691cbbf37
   region: us-east-1
   instance:
   - mysql
   - frontend
   - backend
   
  tasks:
    - name: Install AWS Python libraries
      ansible.builtin.pip:
       name: "{{ item }}"
       state: present
       
      loop:
      - boto3
      - botocore
  
    - name: create ec2 instances
      amazon.aws.ec2_instance:
       name: "{{ item }}"
       instance_type: "{{ instance_type }}"
       image_id: "{{ ami_id}}"
       region: "{{ region }}"
       subnet_id: "{{ subnet_id}}"
       security_group: "{{ sg_id }}"
      loop: "{{ instance }}"
    