- name: create ec2 & r53 through ansible
  hosts: local
  become: true
  connection: local
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      image_id: ami-09c813fb71547fc4f
      subnet_id: ssubnet-0c15405f633ef6962
      sg_id: sg-00397bd41905b6fbf
    loop:
    - mysql
    - frontend
    - backend