- name: create ec2 & r53 through ansible
  hosts: local
  become: true
  connection: local
  vars:
   subnet_id: subnet-090adbff608de6e30
   sg_id:  sg-00397bd41905b6fbf
   instance_type: t3.micro
   ami_id: ami-09c813fb71547fc4f
   instance:
   - mysql
   - frontend
   - backend
   
  tasks:
  - name: install python lib
    ansible.builtin.pip:
     name: "{{ item}}"
     execution: pip3.9
    loop:
    - botocore
    - boto3 

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id}}"
      subnet_id: "{{ subnet_id}}"
      security_group: "{{ sg_id }}"
    loop: "{{ instance }}"
    