- name: vars from files
  hosts: web
  vars_files:
   - course.yaml
  tasks:
   - name: print var1 from file
     ansible.builtin.debug:
     msg: "this is {{course}} course"

   - name: print var2 from file
     ansible.builtin.debug:
     msg: "{{course}} course duration is : {{duration}}"  