- name: vars from inventory file
  hosts: local
  tasks:
   - name: print vars from inventory files
     ansible.builtin.debug:
      msg: "course is :{{course}} , duration= {{duration}} , student:{{student}} "