- name: vars from inventory file
  hosts: web
  tasks:
   - name: print vars from inventory files
     ansible.builtin.debug:
      msg: "course is :{{course}} , duration is : {{duration}} , trainer:{{trainer}} "