- name: variables from command line
  hosts: web
  vars_prompt:
   - name: course
     prompt: enter course name
     private: false

   - name: Duration
     prompt: enter course duration

   - name: student
     prompt: enter student name
   
  tasks: 
   - name: prinnt course information
     ansible.builtin.debug:
        msg: " course is :{{course}} , duration: {{Duration}} , student: {{student}} "
