- name: vars from inventory file
  hosts: local
  connection: local
  tasks:
   - name: print vars from inventory files
     ansible.builtin.debug:
      msg: "course is :{{course}} , duration is : {{duration}} , student:{{student}} "